### ISSUE TITLE
can't run this command ./rcc.sh run

### ISSUE THREAD

**Issue by wulongfeng** [Coleridge-Initiative/rich-context-competition#2]
I'm a new learner of docker, when i run ./rcc.sh run, the result is 
RUN!!!
./rcc.sh: line 503: $6: cannot assign in this way

and i find in config.sh that  DOCKER_CUSTOM_RUN_OPTIONS_IN= (line 34)

does anybody know what value should I give to it?

**Comment by dogrdon** [comment]
Sorry, just seeing this now. You should not have to update any of the DOCKER_CUSTOM_RUN_OPTIONS_IN

You should access  your teams box folder and not use the repository version for setting up your submission.

Please send an email to cusp-richcontext-competition@nyu.edu  to follow up.
